
import java.io.BufferedReader;
import java.io.BufferedWriter;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.util.ArrayList;
import java.util.Scanner;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
/**
 *
 * @author ABC TRADERS
 */
public class Medicines extends javax.swing.JFrame {

     ArrayList<Medicine> allMedicines=new ArrayList<>();
    /**
     * Creates new form Medicines
     */
    public Medicines() {
        initComponents();
        
        readAllData();
        writeAllData();
    }

    
    void writeAllData(){ try{
                MedicineData.setText("");         //MedicineData : variable name of Text area
         for(int i=0;i<allMedicines.size();i++){
             MedicineData.append(allMedicines.get(i).getId()+"   "+allMedicines.get(i).getName()+"   "+allMedicines.get(i).getSellingprice()+"   "+allMedicines.get(i).getBuyingprice()+"   "+allMedicines.get(i).getQuantity()+"   "+allMedicines.get(i).getDescription()+" \n  ");

         }
    }
    catch (Exception e){
        System.out.println("Error: "+ e);
    }
    }

     void readAllData(){
         try{
             File pfile=new File("C:\\Users\\abc\\Documents\\NetBeansProjects\\HospitalManagementSystem\\MedicineData.txt");
             Scanner scanner=new Scanner(pfile);
            //scanner loop to read every next line till end
             while(scanner.hasNextLine()){
                 String data= scanner.nextLine();
                 String[] curData=data.split(";");
                 Medicine medicine= new Medicine();     //javaclass patient object
              
               medicine.setId(Integer.parseInt(curData[0]));          //9301;Bilal;24 our separator is ; so at 0 index  
               medicine.setName((curData[1]));                        //there is id and so on
               medicine.setSellingprice(Integer.parseInt(curData[2]));
               medicine.setBuyingprice(Integer.parseInt(curData[3]));
               medicine.setQuantity(Integer.parseInt(curData[4]));
               medicine.setDescription((curData[5]));
               allMedicines.add(medicine);  //allMedicine is object of jFrame declared above medicine is object of java class declared in home page source 
               
              
             }         
              scanner.close();
         }
       catch(Exception e){
           System.out.println("Error : "+e.getMessage());
       }
       
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        Name = new javax.swing.JLabel();
        SellingPrice = new javax.swing.JLabel();
        sellingprice = new javax.swing.JTextField();
        BuyingPrice = new javax.swing.JLabel();
        buyingprice = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        Quantity = new javax.swing.JLabel();
        description = new javax.swing.JTextField();
        Description = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        MedicineData = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Medicine Information");

        ID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ID.setText("ID :");

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Name.setText("Name :");

        SellingPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SellingPrice.setText("Selling Price :");

        sellingprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellingpriceActionPerformed(evt);
            }
        });

        BuyingPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BuyingPrice.setText("Buying Price : ");

        buyingprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyingpriceActionPerformed(evt);
            }
        });

        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });

        Quantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Quantity.setText("Quantity :");

        description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionActionPerformed(evt);
            }
        });

        Description.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Description.setText("Description :");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 204, 51));
        jButton1.setText("Save ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 255));
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 51, 0));
        jButton4.setText("Remove");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Description)
                                    .addComponent(Name)
                                    .addComponent(ID))
                                .addGap(59, 59, 59)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sellingprice, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buyingprice, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Quantity)
                            .addComponent(SellingPrice)
                            .addComponent(BuyingPrice)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jButton4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SellingPrice)
                    .addComponent(sellingprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuyingPrice)
                    .addComponent(buyingprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Quantity)
                    .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Description)
                    .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addGap(76, 76, 76))
        );

        MedicineData.setColumns(20);
        MedicineData.setRows(5);
        jScrollPane1.setViewportView(MedicineData);

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/capsule.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Medicine Menu");

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 204, 0));
        jButton3.setText("Home");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(41, 41, 41))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void sellingpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellingpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sellingpriceActionPerformed

    private void buyingpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyingpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buyingpriceActionPerformed

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    private void descriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if(id.getText().equals("")||sellingprice.getText().equals("")||name.getText().equals("")||buyingprice.getText().equals("")||description.getText().equals("")||quantity.getText().equals("")){
            JOptionPane.showMessageDialog(null,"All Fields Required");
        }
        else if(checkIDC()){
            JOptionPane.showMessageDialog(null, "ID already exists");
        }
        else{
            try{
                Medicine medicine=new Medicine();
                //saving data in Patient Class
                medicine.setId(Integer.parseInt(id.getText()));          //9301;Bilal;24 our separator is ; so at 0 index
                medicine.setName((name.getText()));                        //there is id and so on
                medicine.setSellingprice(Integer.parseInt(sellingprice.getText()));              //parsing is done here to change string data to integer
                medicine.setBuyingprice(Integer.parseInt(buyingprice.getText()));    //since text area accepts every thing in String form
                medicine.setQuantity(Integer.parseInt(quantity.getText()));
                medicine.setDescription((description.getText()));
                allMedicines.add(medicine);
                saveAllData();
                writeAllData();
                //setting every thing to null for adding new patient
                id.setText("");
                name.setText("");
                buyingprice.setText("");
                sellingprice.setText("");
                quantity.setText("");
                description.setText("");

            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,"ID and Age must be integer"+e.getMessage());
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed
boolean checkIDC(){
         boolean b=true;
         for (int i=0;i<allMedicines.size();i++){
             if(id.getText().equals(allMedicines.get(i).getId()+" ")){
                 b=true; 
             }
             else {
                 b=false;
             }
         }
         
        return b;
    }

void saveAllData(){
         try{
           FileWriter filewriter=new FileWriter("C:\\Users\\abc\\Documents\\NetBeansProjects\\HospitalManagementSystem\\MedicineData.txt");  
          for(int i=0;i<allMedicines.size();i++){
              filewriter.write(allMedicines.get(i).getId()+";"+allMedicines.get(i).getName()+";"+allMedicines.get(i).getSellingprice()+";"+allMedicines.get(i).getBuyingprice()+";"+allMedicines.get(i).getQuantity()+";"+allMedicines.get(i).getDescription()+"   ");
          }
          
          filewriter.close();
         }
         catch(Exception e){
             
         }
     }    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        if(id.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter valid ID");

        }
        else{
            Medicine medicine=null;
            for(int i=0;i<allMedicines.size();i++){
                if(id.getText().equals(allMedicines.get(i).getId()+"")){
                    medicine=allMedicines.get(i);
                    
                }
                break;
            }
            if(medicine==null){
                JOptionPane.showMessageDialog(null,"Not Available \nPlease enter valid");

            }
            else{
                JOptionPane.showMessageDialog(null,"Medicine Information \nName : "+medicine.getName()+"\nSelling Price : "+medicine.getSellingprice()+"\nBuying Price : "+medicine.getBuyingprice()+"\nQuantity : "+medicine.getQuantity()+"\nDescription : "+medicine.getDescription());

            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setVisible(false);
        HomePage homepage=new HomePage();// TODO add your handling code here:
        homepage.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(id.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter valid ID");

        }
        else{
            Medicine medicine=null;
            for(int i=0;i<allMedicines.size();i++){
                if(id.getText().equals(allMedicines.get(i).getId()+"")){
                    medicine=allMedicines.get(i);
                  break;  
                }
               
            }
            if(medicine==null){
                JOptionPane.showMessageDialog(null,"Not Available \nPlease enter valid ID");

            }
            else{
                for(int i=0;i<allMedicines.size();i++){
                if(id.getText().equals(allMedicines.get(i).getId()+"")){
                    medicine.setId(allMedicines.get(i).getId());
                     medicine.setName((allMedicines.get(i).getName()));                        //there is id and so on
                medicine.setSellingprice((allMedicines.get(i).getSellingprice()));              //parsing is done here to change string data to integer
                medicine.setBuyingprice((allMedicines.get(i).getBuyingprice()));    //since text area accepts every thing in String form
                medicine.setQuantity((allMedicines.get(i).getQuantity()));
                medicine.setDescription((allMedicines.get(i).getDescription()));
                    break;
                }
                
            }
                if(medicine==null){
                JOptionPane.showMessageDialog(null,"Not Available \nPlease enter valid");
                        }
                else{
                    allMedicines.remove(medicine);
                JOptionPane.showMessageDialog(null,"Successfully removed");
                MedicineData.setText("");
                
               //readAllData();
               writeAllData();}  }  } }
             //  saveAllData();
          /*   try{
                 FileWriter writer= new FileWriter("C:\\Users\\ABC TRADERS\\Documents\\NetBeansProjects\\HospitalManagementSystem\\MedicineData.txt");

             BufferedWriter bwrite = new BufferedWriter(writer);
             for(Medicine UpdatedLine:allMedicines)
             {
                 bwrite.append((CharSequence) UpdatedLine);
                 bwrite.newLine();
                 
             }
             bwrite.close();
             writer.close();
                }
                catch(Exception e){
                    System.out.println("Error"+e);
                }}
    }//GEN-LAST:event_jButton4ActionPerformed
 }}
 
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Medicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Medicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Medicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Medicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Medicines().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BuyingPrice;
    private javax.swing.JLabel Description;
    private javax.swing.JLabel ID;
    private javax.swing.JTextArea MedicineData;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Quantity;
    private javax.swing.JLabel SellingPrice;
    private javax.swing.JTextField buyingprice;
    private javax.swing.JTextField description;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField sellingprice;
    // End of variables declaration//GEN-END:variables
}
